name: Build and deploy Zola website

env:
  BASE_URL: https://aemshomy.github.io/website/
  OUTPUT_DIR: public

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6.0.1
        with:
          submodules: recursive

      - name: Build Zola
        uses: ./.github/actions/build
        with:
          build_flags: --base-url "$BASE_URL" --output-dir "$OUTPUT_DIR"

      - name: Upload Pages Artifact
        uses: actions/upload-artifact@v4
        with:
          path: $OUTPUT_DIR
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
