name: Build and deploy Zola website

env:
  BASE_URL: https://aemshomy.github.io/website/
  OUTPUT_DIR: public

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6.0.1
        with:
          submodules: recursive

      - name: build zola
        uses: ./.github/actions/build
        with:
          build_flags: --base-url ${{ env.BASE_URL }} --output-dir ${{ env.OUTPUT_DIR }}

      - name: upload pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ${{ env.OUTPUT_DIR }}
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
